-- 迁移 0047：调用日志的定价版本快照（price_version）
--
-- 意图（Why）：
--   定价规则是【就地更新】的：model_prices / channel_model_costs 都只保存"当前值"，
--   站长一改价，历史账单就再也无法说明"那一笔当时按什么价算的"。
--   本列记录每条调用日志所用的定价版本标识（规则 ID + 规则更新时间，形如
--   "123@1727000000"），为"改价后旧账仍可按旧价定位/复算"提供锚点。
--
-- 为什么只存版本标识、不存完整价格快照：
--   全量快照（把当时的输入/输出/按次价整份拷进每条日志）会让高频写入的
--   usage_logs 体积成倍膨胀；而版本标识已足以在需要时定位到"哪一版规则"，
--   复算所需的完整价格可由规则表 + 版本时间还原，是本表两种取舍里更轻的一种。
--
-- 兼容性：
--   NOT NULL + 常量默认值，SQLite 允许对已有表直接 ADD COLUMN；
--   历史行一次性获得空串（表示"未采集"），不影响任何既有查询与计费行为。
--
-- 流转（Flow）：
--   relay.recordUsage 组装 UsageLog 时写入本次计费的规则版本
--     → store/usage_log_repo.go 的 Create 落库、scanUsageLog 读出
--     → 对账 / 账单追溯时按该标识回到定价规则的对应版本
--
-- 扩展（Extend）：
--   若后续需要"逐值复算"，再单独引入定价历史表（本列作为其外键即可），
--   不要在 usage_logs 上追加更多价格列。

ALTER TABLE usage_logs ADD COLUMN price_version TEXT NOT NULL DEFAULT '';
